# __Numpy__

Numerical Python의 줄임말이기도 한 Numpy는, 고성능의 수치계산을 위한 라이브러리 <br>
Numpy는 벡터 및 행렬 연산에 있어서 매우 편리한 기능을 제공 <br>
데이터분석을 할 때 사용되는 라이브러리인 pandas와 matplotlib의 기반으로 사용되기도 함
<br><br>
numpy를 활용하기 위해서는 가장 먼저 라이브러리 설치가 필요하다.

In [ ]:
# install
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
# import
import numpy as np

## Numpy 기초
행렬 및 벡터 연산을 위해선 다차원 array를 사용해야 한다. <br>
Numpy에서 이러한 다차원 array형태인 핵심적인 객체를 ndarray라고 부른다. <br><br>

### array 객체의 속성 

* ndarray.ndim: 차원의 수 (rank) 반환
* ndarray.shape: 각 차원에 속한 원소의 수를 튜플 형태로 반환
* ndarray.size: 배열에 있는 총 갯수 반환
* ndarray.dtype: 자료형의 종류 반환 
* ndarray.itemsize: 배열의 데이터 사이즈 반환
* ndarray.T: 전치된 결과 반환

## Numpy 배열 만들기 
* array(리스트 or 튜플) 
* arange()
* zeros()
* ones()
* full()
* eye()
* random()

In [ ]:
# 1. array(리스트)로 1차원 배열 만들기
list1 = [1,2,3,4]
a1 = np.array(list1)
print(a)
print(a.shape) 

[1 2 3 4]
(4,)


In [ ]:
# 2. array(리스트)로 2차원 배열 만들기
a2 = np.array([[1,2,3], [4,5,6]])
print(a2)
print(a2.shape) 

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
# 3. arange()로 1차원 배열 만들기
a3 = np.arange(10) # 0부터 9까지 숫자 배열 생성
print(a3)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 4. arange()로 1차원 배열 만들기
a4 = np.arange(3,11,2) # 3부터 10까지 공차가 2인 등차수열 생성
print(a4)

[3 5 7 9]


In [ ]:
# 5. arange()로 1차원 배열 만들기
a5 = np.arange(2.0, 9.8, 0.3, dtype = np.float64) # 자료형이 실수인 등차수열 생성 
print(a5)

[2.  2.3 2.6 2.9 3.2 3.5 3.8 4.1 4.4 4.7 5.  5.3 5.6 5.9 6.2 6.5 6.8 7.1
 7.4 7.7 8.  8.3 8.6 8.9 9.2 9.5 9.8]


In [ ]:
# 6. zeros(튜플)로 1차원 배열 만들기 
a6 = np.zeros((3,)) # == np.zeros(3) 모든 값이 0인 배열 생성 
print(a6)

[0. 0. 0.]


In [ ]:
# 7. zeros(튜플)로 n차원 배열 만들기
a7 = np.zeros((4,3)) # 모든 값이 0인 4*3 배열 생성 
print(a7)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 8. ones(튜플)로 n차원 배열 만들기
a8 = np.ones((4,3)) # 모든 값이 1인 4*3 배열 생성
print(a8)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# 9. full()로 n차원 배열 만들기
a9 = np.full((2,2), 5) # 모든 값이 5인 2*2 배열 생성
print(a9)

[[5 5]
 [5 5]]


In [ ]:
# 10. eye(n)로 n*n 배열 만들기
a10 = np.eye(4)  # 4*4 항등행렬 생성 
print(a10)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# 11. random(튜플)로 배열 만들기 
a11 = np.random.random((3,4)) # 0.0 ~ 1.0 사이 난수로 3*4 배열 생성 
print(a11)

[[0.02650707 0.24937443 0.7211914  0.27729958]
 [0.94839903 0.13203473 0.91615236 0.50268781]
 [0.61566279 0.76852241 0.07988767 0.00811611]]


## Numpy 배열 모양 바꾸기
* reshape()

In [ ]:
# 1. reshape()으로 차원 변경 
b1 = np.arange(10) # 1차원 배열 생성 
print(b1)
b2 = b1.reshape(2,5)  # 차원 변경 
print(b2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Numpy 인덱싱


*   ndarray[index]
*   ndarray[index1, index2]
*   ndarray[index1:index2]
*   ndarray[[index1, index2],[index3, index4]]
*   boolean indexing



In [ ]:
# 1. ndarray[index] 이용 
c1 = np.arange(10)
print(c1)
c1[2]  # 배열의 첫항은 0번으로 인덱스 시작 

[0 1 2 3 4 5 6 7 8 9]


2

In [ ]:
# 2. ndarray[index1, index2] 이용
c2 = c1.reshape(5,2)
print(c2)
c2[3,1]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


7

In [ ]:
# 3. ndarray[index1:index2] 이용
print(c1[0:3]) # 0 ~ 2번 인덱스까지 출력 
print(c2[0:3, 0:1]) # 0 ~ 2번 행 * 0번 열 출력

[0 1 2]
[[0]
 [2]
 [4]]


In [ ]:
# 4. ndarray[[index1, index2],[index3, index4]] 이용 
print(c2)
print(c2[[0, 2], [1, 1]])  # 0번 행*1번 열 and 2번 행*1번 열

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[1 5]


In [ ]:
# 5. boolean indexing 이용 
list = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
c5 = np.array(list)  # 리스트를 이용하여 배열 생성 
 
bool_array = np.array([
    [False,  True, False],
    [True, False,  True],
    [False,  True, False]
])  # 불린 값을 이용하여 같은 크기의 배열 생성 
 
c6 = c5[bool_array]  # bool_array를 c5 배열에 적용 
print(c6)  # True인 인덱스의 값만 출력 

[2 4 6 8]


In [ ]:
# 추가. 수식으로 인덱싱 가능 
c7 = c5[ c5 % 2 == 0]  # 짝수 값을 가지는 인덱스만 남김 
print(c7)

[2 4 6 8]


## Numpy 연산
* 연산자 사용 (+, -, *, /, % 등)
* method function 사용 
 * axis = 0: 열끼리 계산, axis = 1: 행끼리 계산

***배열 간 연산이 가능하다는 것이 넘파이의 주요 특징!*** 

In [ ]:
# 1. 더하기 
d = np.array([1,2,3])
e = np.array([4,5,6])

f = d + e  # == ( d = np.add(d, e) )
print(f)

[5 7 9]


In [ ]:
# 2. 빼기 
f = d - e # == ( f = np.subtract(d, e) )
print(f)

[-3 -3 -3]


In [ ]:
# 3. 곱하기 
f = d * e  # == ( f = np.multiply(d, e) )
print(f)

[ 4 10 18]


In [ ]:
# 4. 나누기 
f = d / e  # ( f = np.divide(d, e) )
print(f)

[0.25 0.4  0.5 ]


In [ ]:
# 5. 그 외 함수들 
print(d)
print(d.mean())  # 평균
print(d.sum())  # 합
print(d.std())  # 표준편차 
print(d.var())  # 분산 
print(d.min())  # 최솟값
print(d.max())  # 최댓값

[1 2 3]
2.0
6
0.816496580927726
0.6666666666666666
1
3


In [ ]:
# 6. 그 외 함수들2
g = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(g)
print(g.cumsum(0))  # 행을 기준으로 누적합
print(g.cumsum(1))  # 열을 기준으로 누적합
print(g.cumprod(0))  # 행을 기준으로 누적곱
print(g.cumprod(1))  # 열을 기준으로 누적곱

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
[[  1   2   3]
 [  4  10  18]
 [ 28  80 162]]
[[  1   2   6]
 [  4  20 120]
 [  7  56 504]]


## 선형대수학 in Numpy
* numpy.diag: 대각선의 값 추출
* numpy.dot: 행렬 곱셈
* numpy.trace: 대각합
* numpy.linalg.det: 행렬식
* numpy. linalg.eig: 고유값과 고유벡터 계산
* numpy.linalg.inv: 역행렬 계산